Hatena2009-02-07
code:hatena
 <body>
 *1233957054* Cured!
 I would like to think!
 
 <hr>
 
 Well, I just went down to the first floor to check the mail and came back, but my heart is still racing... Should I stay home quietly for the rest of the day?
 
 <hr>
 
 I ended up sleeping for about three days, and although I finally recovered, I am in a state where I can't get anything done, only feeling more and more agitated. Slowly, slowly.
 
 <hr>
 
 My agitation and anxiety are heightened because I am not secreting enough serotonin! So for now, try belly breathing.
 
 <hr>
 
 19:00. I ended up falling asleep twice and waking up at this hour because I was out of rhythm.
 
 *1234017874* No particular overhead in calling functions that could throw an exception
 Yes, I wrote this code when there was a discussion on Twitter earlier about whether there is a difference in calling cost between Python functions that throw exceptions and those that don't, and I'm going to paste it because it's useless to bury it like this.
 
 >|python|
 import timeit
 
 print timeit.Timer("foo(1)", setup="""
 def foo(x):
     if x:
         return None
     else:
         return x
 """).repeat()
 
 print timeit.Timer("bar(1)", setup="""
 def bar(x):
     if x:
         return None
     else:
         raise NotImplemented
 """).repeat()
 ||<
 
 >||
 [0.24111700057983398, 0.22863888740539551, 0.22955012321472168]
 [0.23151803016662598, 0.23359298706054688, 0.2297508716583252]
 ||<
 
 *1234032819*MaganicWarsFinal
 http://uploads.ungrounded.net/207000/207756_MaganicWarsFinal.swf
 
 There is one strange sound effect, but it was quite interesting as well.
 
 <img src="http://gyazo.com/3a1b61c1282eebde7fcb087af2da4913.png">
 </body>

[Hatena Diary 2009-02-07 https://nishiohirokazu.hatenadiary.org/archive/2009/02/07]