{
  "id": "606ec39001213e001c73442e",
  "title": "Fixed: VSCodeでPythonの定義へのジャンプが使えなくなった",
  "created": 1617871764,
  "updated": 1617874712,
  "lines": [
    {
      "id": "606ec39001213e001c73442e",
      "text": "Fixed: VSCodeでPythonの定義へのジャンプが使えなくなった",
      "userId": "582e63d27c56960011aff09e",
      "created": 1617871764,
      "updated": 1617874102
    },
    {
      "id": "606ece5eaff09e00009d9acd",
      "text": "気が付いたらPythonで定義へのジャンプができなくなっていて不便で困った。",
      "userId": "582e63d27c56960011aff09e",
      "created": 1617874526,
      "updated": 1617874557
    },
    {
      "id": "606ece5eaff09e00009d9ace",
      "text": "",
      "userId": "582e63d27c56960011aff09e",
      "created": 1617874526,
      "updated": 1617874526
    },
    {
      "id": "606ec394aff09e00009e5146",
      "text": "一旦Python関連の拡張をアンインストールしてVSCodeを再起動し、Pythonにオススメの拡張があるよ、というダイアログが出るのでそれを入れたら直った。",
      "userId": "582e63d27c56960011aff09e",
      "created": 1617871764,
      "updated": 1617874226
    },
    {
      "id": "606ec395aff09e00009e5148",
      "text": "",
      "userId": "582e63d27c56960011aff09e",
      "created": 1617871765,
      "updated": 1617871765
    },
    {
      "id": "606ec395aff09e00009e5149",
      "text": "[https://gyazo.com/54f26be954edf2014e144e89a3141f9f]",
      "userId": "582e63d27c56960011aff09e",
      "created": 1617871766,
      "updated": 1617871779
    },
    {
      "id": "606ec3a2aff09e00009e514a",
      "text": "",
      "userId": "582e63d27c56960011aff09e",
      "created": 1617871779,
      "updated": 1617871779
    },
    {
      "id": "606ec3d3aff09e00009e514b",
      "text": "[https://gyazo.com/1146cab90998b04c45a547499fd6b73d]",
      "userId": "582e63d27c56960011aff09e",
      "created": 1617871828,
      "updated": 1617871829
    },
    {
      "id": "606ec3d5aff09e00009e514c",
      "text": "",
      "userId": "582e63d27c56960011aff09e",
      "created": 1617871829,
      "updated": 1617871829
    },
    {
      "id": "606ecd34aff09e00009d9ac7",
      "text": "原因を確定させるための実験をしてまた壊れたら嫌なのでやらないが、関連する情報をメモしておく",
      "userId": "582e63d27c56960011aff09e",
      "created": 1617874229,
      "updated": 1617874260
    },
    {
      "id": "606ecdcdaff09e00009d9ac9",
      "text": "　Pylanceを入れてみたことが怪しい",
      "userId": "582e63d27c56960011aff09e",
      "created": 1617874381,
      "updated": 1617874393
    },
    {
      "id": "606ecd54aff09e00009d9ac8",
      "text": "　[https://gyazo.com/ed9698d6fdccc8b9f3309d38d157ca7b]",
      "userId": "582e63d27c56960011aff09e",
      "created": 1617874260,
      "updated": 1617874374
    },
    {
      "id": "606ecdc6aff09e00009e514d",
      "text": "　詳細はもうわからないが、入れた直後に問題が起きていれば流石に気づいたのでは…",
      "userId": "582e63d27c56960011aff09e",
      "created": 1617874374,
      "updated": 1617874448
    },
    {
      "id": "606ece10aff09e00009d9aca",
      "text": "　その後しばらくの間に何度かVSCodeをアップデートしたり再起動したりした",
      "userId": "582e63d27c56960011aff09e",
      "created": 1617874449,
      "updated": 1617874473
    },
    {
      "id": "606ece28aff09e00009d9acb",
      "text": "　僕は開発しているものによってTypeScriptを書いてる時期とPythonを書いてる時期があるので、TypeScriptの時期にしたアップデートでPythonの挙動が変わった場合はすぐに気づかなさそう。",
      "userId": "582e63d27c56960011aff09e",
      "created": 1617874473,
      "updated": 1617874712
    },
    {
      "id": "606ec394aff09e00009e5147",
      "text": "",
      "userId": "582e63d27c56960011aff09e",
      "created": 1617871765,
      "updated": 1617871765
    }
  ]
}